dist: xenial
language: python
sudo: false

python:
  - 3.6.11
  - 3.7.8
  - 3.8.4
  - 3.8-dev
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
    - python: 3.8-dev

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
  - pip install .       # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v --cov-report=xml --cov=intergalactic # Test against installed code

after_success:
  - codecov
